% Autoencoder hyper-parameters. DO NOT MODIFY
% ONLY USED FOR DESCRIPTION PURPOSES

parnet = struct(...
    'units',[60 100 50 6],...   % input + hidden units(last is the encoding layer)
    'activations',{{'sigm','sigm','sigm'}},... % activation of hidden layer units
    'pretrain','rbm',...    % initialization/pretrain mode: rbm (restricted boltmann machine-based pretraining)/ae(stacked autoncoders)/rand (random)
    'preae_maxepoch',50,... % for 'ae' pretraining, number of epochs for each layer
    'vgaus',1,...   % for 'rbm' pretraining, gaussian visible units
    'hgaus',0,...   % for 'rbm' pretraining, gaussian hidden units
    'pairsim',0,... % segmental AE (SAE) using similarity heuristic 
    'shid',0,...    % segmental contractive AE (SCAE) using similarity heuristic
    'noisy',0,...   % denoising AE (DAE)
    'binarize',0,...    % binarize encodings in the fwd pass: 1) threshold 0.5; 2) threshold stochastically
    'forceBin',0,...    % force binarization: 1) add noise to encoding layer input; 2) additional entropy cost term
    'noiseVariance',16,...  % for forceBin=1, variance of the noise
    'entropyWeight',1,...   % for forceBin=2, weight of the entropy term
    'sparsepen',0,...   % sparsity penalty (beta)
    'sparsepar',0.05,...    % sparsity parameter (rho)
    'batchsize',1000,...
    'maxepoch',10,...       % max number of training epochs
    'optimization','cgd',...    % cgd/sgd
    'cost','mse',...
    'dropout',0,...
    'learningRate',0.1,...          % SGD parameters
    'learningRateDecay',0.99,...    %%
    'momentum',0.9,...              %%
    'weightDecay',0.0001,...
    'rbmparam',struct(...          % hyep-parameters of restricted boltzmann machine    
        'vgaus',0,...              % boolean to indicate whether visible units should be considered as gaussian distribited variables
        'hgaus',0,...
        'batchsize',50,...
        'maxepoch',10,...
        'epsilonw',0.1,...
        'epsilonvb',0.1,...
        'epsilonhb',0.1,...
        'weightcost',0.0002,...
        'initialmomentum',0.5,...
        'finalmomentum',0.9...
        ),...
    'rbmhgausparam',struct(...
        'vgaus',0,...
        'hgaus',1,...
        'batchsize',50,...
        'maxepoch',20,...
        'epsilonw',0.001,...
        'epsilonvb',0.001,...
        'epsilonhb',0.001,...
        'weightcost',0.0002,...
        'initialmomentum',0.5,...
        'finalmomentum',0.9...
        ),...
    'rbmvgausparam',struct(...
        'vgaus',1,...
        'hgaus',0,...
        'batchsize',50,...
        'maxepoch',20,...
        'epsilonw',0.001,...
        'epsilonvb',0.001,...
        'epsilonhb',0.001,...
        'weightcost',0.0002,...
        'initialmomentum',0.5,...
        'finalmomentum',0.9...
        )...
);
