% DNN hyper-parameters. DO NOT MODIFY
% ONLY USED FOR DESCRIPTION PURPOSES

parnet=struct(...
     'units',[NaN 2000 2000 2000 2000 NaN],... % input + hidden + output units 
    'activations',{{'relu','relu','relu','relu','softmax'}},... hydden and output layer node activations. Possible activations are relu, sigm, tanh, linear, softmax
    'pretrain','rand',...   % other options 'rbm' or 'aam', or 'loadnet'. 'aam' for Acoustic to Articulatory Mapping - based pretraining
    'outputInit_maxepoch',5,... %  if 'rbm'/'aam' pretraining, number of epochs to initialize last layer weights. default is 5
    'vgaus',1,... % boolean indicating whether the input features have to be considered Gaussian distributed
    'hgaus',0,... % boolean indicating whether the hidden units have to be considered Gaussian distributed
    'batchsize',1000,...
    'maxepoch',20,... %for mngu0 50 - timit 20-25 % max number of training epochs
    'optimization','sgd',... % sgd or cgd
    'cost','ce_softmax',... % cost function. ce_softmax/ce_logistic/mse
    'dropout',0,... % if = 1, dropout is applied ( "suppression" probabilities are fixed in nnCost)  
    'learningRate',0.1,...  %original timit 0.1
    'learningRateDecay',.75,... %for mngu0 .99 - timit .8   
    'learningRateMin',.0005,...
    'momentum',0.9,...  %momentum 0.9
    'weightDecay',0.0001,...  %for mngu0 0.0001 - timit 0
    'earlystop',1,...
    'multitask',struct(... % hyeperparams for multi-task learning
        'mtktype','joint_top',... % do not change
        'firstnode',1,...
        'lastnode',NaN,...
        'cost2','mse',... %alternatives are 'ce_softmax' and  'ce_logistic'
        'ccost2',{{'mse'}},...
        'cactivations2',{{'relu'}},... % actovation of the additional layer(s) specific for the secondary target(s)
        't2w',0.1... % weight fiven to the secondary task
        ),...        % pretraining hyperparams
    'rbmparam',struct(...
        'vgaus',0,...
        'hgaus',0,...
        'batchsize',50,...
        'maxepoch',75,...
        'epsilonw',0.1,...
        'epsilonvb',0.1,...
        'epsilonhb',0.1,...
        'weightcost',0.0002,...
        'initialmomentum',0.5,...
        'finalmomentum',0.9...
        ),...
    'rbmhgausparam',struct(...
        'vgaus',0,...
        'hgaus',1,...
        'batchsize',50,...
        'maxepoch',225,...
        'epsilonw',0.001,...
        'epsilonvb',0.001,...
        'epsilonhb',0.001,...
        'weightcost',0.0002,...
        'initialmomentum',0.5,...
        'finalmomentum',0.9...
        ),...
    'rbmvgausparam',struct(...
        'vgaus',1,...
        'hgaus',0,...
        'batchsize',50,...
        'maxepoch',225,...
        'epsilonw',0.001,...
        'epsilonvb',0.001,...
        'epsilonhb',0.001,...
        'weightcost',0.0002,...
        'initialmomentum',0.5,...
        'finalmomentum',0.9...
        )...    
    );